### ISSUE TITLE
cannot find module popsicle

### ISSUE THREAD

**Issue by elmerbulthuis** [blakeembrey/popsicle-retry#9]
I get a `TypeScript error: node_modules/popsicle-retry/dist/index.d.ts(2,50): Error TS2307: Cannot find module 'popsicle'`.

this error is thrown by the following code in `dist/index.d.ts`:

```typescript
import { Request, Response, PopsicleError } from 'popsicle';
```

I have installed typings, typings-core depends on typings and typings-core depends on popsicle-retry.

help! :-)

**Comment by blakeembrey** [comment]
Did you install the typings for `popsicle`? See https://github.com/blakeembrey/popsicle#typescript.
